jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ["18","20"]
    runs-on: $ { { matrix.os } }
    steps:
      -uses: actions/checkout@4v
      -uses: actions/setup-node@v4
       with:
         node-version: $ { { matrix.node } }

