name: say hello
on: push
jobs:
  greet:
    runs-on: ubuntu-lastest
    steps:
      -run:echo "hello,actions!"
steps:
  - uses: actions/checkout@v4
  - name: Show the commit
    run: echo "Commit: $GITHUB_SHA"
  - name: List the files
    run: ls -la

